# Generated by Django 4.2.2 on 2023-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryPlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('distance_from_sun', models.IntegerField(default=0)),
                ('year_length', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('moons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['distance_from_sun'],
            },
        ),
    ]
