# Generated by Django 4.2.2 on 2023-07-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryplanet',
            name='distance_from_sun',
            field=models.BigIntegerField(default=0),
        ),
    ]
