# Generated by Django 4.2.2 on 2023-07-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_primaryplanet_distance_from_sun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('year_of_discovery', models.IntegerField(default=0)),
                ('discovered_by', models.CharField(max_length=150)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moon', to='main_app.primaryplanet')),
            ],
        ),
    ]
